services: 
  backend:
    build: ./backend
    container_name: album_backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env.prod
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: album_frontend
    command: npm run start
    volumes:
      - ./frontend:/app
    env_file:
      - .env.prod
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  static_volume:
  media_volume: